# Generated by Django 3.2.6 on 2021-08-24 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livro',
            fields=[
                ('id_livro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_da_edicao', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('pags', models.IntegerField()),
                ('editora', models.CharField(max_length=255)),
                ('isercao_no_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
