# Generated by Django 3.2.6 on 2021-08-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='title',
            new_name='titulo',
        ),
    ]
