# Generated by Django 3.2.6 on 2021-08-25 22:44

from django.db import migrations, models
import livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_title_livro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa_livro',
            field=models.ImageField(blank=True, null=True, upload_to=livros.models.uploadCapalivro),
        ),
    ]
